#!/bin/bash

# =============================================================================
# VPS Resource Alert Setup
# Email notifications for CPU, Memory, and Disk usage
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         VPS Resource Alert Setup                         ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo

# Email configuration
print_status "Email Configuration for Alerts"
echo

read -p "Your email address for alerts: " ALERT_EMAIL
read -p "SMTP server (e.g., smtp.gmail.com): " SMTP_SERVER
read -p "SMTP port (default: 587): " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-587}
read -p "SMTP username: " SMTP_USER
read -sp "SMTP password: " SMTP_PASSWORD
echo
echo

# Alert thresholds
print_status "Alert Thresholds Configuration"
echo

read -p "CPU threshold % (default: 80): " CPU_THRESHOLD
CPU_THRESHOLD=${CPU_THRESHOLD:-80}

read -p "Memory threshold % (default: 85): " MEMORY_THRESHOLD
MEMORY_THRESHOLD=${MEMORY_THRESHOLD:-85}

read -p "Disk threshold % (default: 80): " DISK_THRESHOLD
DISK_THRESHOLD=${DISK_THRESHOLD:-80}

echo

# Create monitoring script
MONITOR_SCRIPT="/root/scripts/check_resources.sh"

print_status "Creating resource monitoring script..."

cat > "$MONITOR_SCRIPT" << 'EOFMONITOR'
#!/bin/bash

# VPS Resource Monitor
# Auto-generated by setup_resource_alerts.sh

# Configuration (replaced by setup script)
ALERT_EMAIL="ALERT_EMAIL_PLACEHOLDER"
SMTP_SERVER="SMTP_SERVER_PLACEHOLDER"
SMTP_PORT="SMTP_PORT_PLACEHOLDER"
SMTP_USER="SMTP_USER_PLACEHOLDER"
SMTP_PASSWORD="SMTP_PASSWORD_PLACEHOLDER"

CPU_THRESHOLD=CPU_THRESHOLD_PLACEHOLDER
MEMORY_THRESHOLD=MEMORY_THRESHOLD_PLACEHOLDER
DISK_THRESHOLD=DISK_THRESHOLD_PLACEHOLDER

# Get current values
CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}' | cut -d. -f1)
MEMORY_USAGE=$(free | grep Mem | awk '{printf("%.0f", $3/$2 * 100)}')
DISK_USAGE=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')

# Hostname and IP
HOSTNAME=$(hostname)
SERVER_IP=$(curl -4 -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')

# Alert flags
ALERT_TRIGGERED=false
ALERT_MESSAGES=""

# Check CPU
if [ "$CPU_USAGE" -ge "$CPU_THRESHOLD" ]; then
    ALERT_TRIGGERED=true
    ALERT_MESSAGES="${ALERT_MESSAGES}⚠️  CPU: ${CPU_USAGE}% (threshold: ${CPU_THRESHOLD}%)\n"
fi

# Check Memory
if [ "$MEMORY_USAGE" -ge "$MEMORY_THRESHOLD" ]; then
    ALERT_TRIGGERED=true
    ALERT_MESSAGES="${ALERT_MESSAGES}⚠️  Memory: ${MEMORY_USAGE}% (threshold: ${MEMORY_THRESHOLD}%)\n"
fi

# Check Disk
if [ "$DISK_USAGE" -ge "$DISK_THRESHOLD" ]; then
    ALERT_TRIGGERED=true
    ALERT_MESSAGES="${ALERT_MESSAGES}⚠️  Disk: ${DISK_USAGE}% (threshold: ${DISK_THRESHOLD}%)\n"
fi

# Send alert if triggered
if [ "$ALERT_TRIGGERED" = true ]; then
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

    # Email subject
    SUBJECT="🚨 VPS Resource Alert - $HOSTNAME"

    # Email body
    BODY="Resource Alert Triggered

Server: $HOSTNAME ($SERVER_IP)
Time: $TIMESTAMP

ALERTS:
$ALERT_MESSAGES

Current Usage:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CPU:    ${CPU_USAGE}% (threshold: ${CPU_THRESHOLD}%)
Memory: ${MEMORY_USAGE}% (threshold: ${MEMORY_THRESHOLD}%)
Disk:   ${DISK_USAGE}% (threshold: ${DISK_THRESHOLD}%)

Top Processes by CPU:
$(ps aux --sort=-%cpu | head -6 | tail -5)

Top Processes by Memory:
$(ps aux --sort=-%mem | head -6 | tail -5)

Disk Usage:
$(df -h / | tail -1)

Memory Details:
$(free -h)

Docker Containers:
$(docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Size}}' 2>/dev/null | head -10)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Action Required:
1. Check top processes consuming resources
2. Restart heavy containers if needed
3. Clear old logs/backups if disk is full
4. Consider scaling up VPS if consistently high

Login to server:
ssh root@$SERVER_IP
"

    # Send email using Python SMTP
    python3 << EOFPYTHON
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import sys

try:
    msg = MIMEMultipart()
    msg['From'] = "$SMTP_USER"
    msg['To'] = "$ALERT_EMAIL"
    msg['Subject'] = "$SUBJECT"

    msg.attach(MIMEText("""$BODY""", 'plain'))

    server = smtplib.SMTP('$SMTP_SERVER', $SMTP_PORT)
    server.starttls()
    server.login("$SMTP_USER", "$SMTP_PASSWORD")

    server.send_message(msg)
    server.quit()

    print("[$(date)] Alert email sent successfully to $ALERT_EMAIL")
    sys.exit(0)
except Exception as e:
    print(f"[$(date)] Failed to send email: {e}")
    sys.exit(1)
EOFPYTHON

    # Log alert
    echo "[$(date)] ALERT: CPU=${CPU_USAGE}% MEM=${MEMORY_USAGE}% DISK=${DISK_USAGE}%" >> /var/log/resource_alerts.log
else
    # Everything OK - just log
    echo "[$(date)] OK: CPU=${CPU_USAGE}% MEM=${MEMORY_USAGE}% DISK=${DISK_USAGE}%" >> /var/log/resource_checks.log
fi
EOFMONITOR

# Replace placeholders
sed -i "s|ALERT_EMAIL_PLACEHOLDER|$ALERT_EMAIL|g" "$MONITOR_SCRIPT"
sed -i "s|SMTP_SERVER_PLACEHOLDER|$SMTP_SERVER|g" "$MONITOR_SCRIPT"
sed -i "s|SMTP_PORT_PLACEHOLDER|$SMTP_PORT|g" "$MONITOR_SCRIPT"
sed -i "s|SMTP_USER_PLACEHOLDER|$SMTP_USER|g" "$MONITOR_SCRIPT"
sed -i "s|SMTP_PASSWORD_PLACEHOLDER|$SMTP_PASSWORD|g" "$MONITOR_SCRIPT"
sed -i "s|CPU_THRESHOLD_PLACEHOLDER|$CPU_THRESHOLD|g" "$MONITOR_SCRIPT"
sed -i "s|MEMORY_THRESHOLD_PLACEHOLDER|$MEMORY_THRESHOLD|g" "$MONITOR_SCRIPT"
sed -i "s|DISK_THRESHOLD_PLACEHOLDER|$DISK_THRESHOLD|g" "$MONITOR_SCRIPT"

chmod +x "$MONITOR_SCRIPT"

print_success "Monitoring script created: $MONITOR_SCRIPT"

# Setup cron job
print_status "Setting up cron job (checks every 15 minutes)..."

CRON_JOB="*/15 * * * * $MONITOR_SCRIPT"

# Check if already exists
if crontab -l 2>/dev/null | grep -q "$MONITOR_SCRIPT"; then
    print_warning "Cron job already exists - updating..."
    crontab -l 2>/dev/null | grep -v "$MONITOR_SCRIPT" | crontab -
fi

(crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
print_success "Cron job added (runs every 15 minutes)"

# Test email
echo
print_warning "Send test email now? (Y/n)"
read -n 1 -r
echo

if [[ ${REPLY:-Y} =~ ^[Yy]$ ]]; then
    print_status "Sending test email..."

    # Temporarily lower thresholds to trigger alert
    sed -i "s|CPU_THRESHOLD=$CPU_THRESHOLD|CPU_THRESHOLD=0|g" "$MONITOR_SCRIPT"
    sed -i "s|MEMORY_THRESHOLD=$MEMORY_THRESHOLD|MEMORY_THRESHOLD=0|g" "$MONITOR_SCRIPT"
    sed -i "s|DISK_THRESHOLD=$DISK_THRESHOLD|DISK_THRESHOLD=0|g" "$MONITOR_SCRIPT"

    # Run monitor
    $MONITOR_SCRIPT

    # Restore thresholds
    sed -i "s|CPU_THRESHOLD=0|CPU_THRESHOLD=$CPU_THRESHOLD|g" "$MONITOR_SCRIPT"
    sed -i "s|MEMORY_THRESHOLD=0|MEMORY_THRESHOLD=$MEMORY_THRESHOLD|g" "$MONITOR_SCRIPT"
    sed -i "s|DISK_THRESHOLD=0|DISK_THRESHOLD=$DISK_THRESHOLD|g" "$MONITOR_SCRIPT"

    print_success "Test email sent! Check your inbox: $ALERT_EMAIL"
fi

# Create manual check script
cat > /root/scripts/check_resources_now.sh << 'EOFCHECK'
#!/bin/bash
# Quick resource check
echo "Current VPS Resources:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CPU Usage:"
top -bn1 | grep "Cpu(s)"
echo
echo "Memory Usage:"
free -h
echo
echo "Disk Usage:"
df -h /
echo
echo "Top 5 CPU Processes:"
ps aux --sort=-%cpu | head -6
echo
echo "Top 5 Memory Processes:"
ps aux --sort=-%mem | head -6
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
EOFCHECK

chmod +x /root/scripts/check_resources_now.sh

echo
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║       Resource Alert Setup Complete!                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo
echo "📧 Email Alerts:"
echo "   Recipient: $ALERT_EMAIL"
echo "   Check frequency: Every 15 minutes"
echo
echo "⚠️  Alert Thresholds:"
echo "   CPU: ${CPU_THRESHOLD}%"
echo "   Memory: ${MEMORY_THRESHOLD}%"
echo "   Disk: ${DISK_THRESHOLD}%"
echo
echo "📋 Management:"
echo "   Manual check: /root/scripts/check_resources_now.sh"
echo "   View alert log: tail -f /var/log/resource_alerts.log"
echo "   View check log: tail -f /var/log/resource_checks.log"
echo "   Edit thresholds: nano $MONITOR_SCRIPT"
echo
print_success "You will receive email alerts when thresholds are exceeded!"
echo
