#!/bin/bash

# =============================================================================
# Automated Backup Setup for V5
# =============================================================================
#
# This script sets up:
# ✅ Daily automated backups
# ✅ S3 upload integration
# ✅ Email notifications (optional)
# ✅ Backup retention policy
#
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Determine project directory
if [[ -d "/root/scripts/mautic-n8n-stack-v5" ]]; then
    PROJECT_DIR="/root/scripts/mautic-n8n-stack-v5"
elif [[ -d "/root/scripts/mautic-n8n-stack" ]]; then
    PROJECT_DIR="/root/scripts/mautic-n8n-stack"
else
    print_error "Project directory not found"
    exit 1
fi

BACKUP_SCRIPT="$PROJECT_DIR/scripts/daily_backup.sh"

echo
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║           Automated Backup Setup - V5                    ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo

# =============================================================================
# S3 CONFIGURATION
# =============================================================================

print_status "Configuring AWS S3 backup..."
echo

read -p "Enable S3 backups? (Y/n): " -n 1 -r
echo
ENABLE_S3=${REPLY:-Y}

if [[ $ENABLE_S3 =~ ^[Yy]$ ]]; then
    read -p "AWS Access Key ID: " AWS_ACCESS_KEY_ID
    read -sp "AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
    echo
    read -p "S3 Bucket Name: " S3_BUCKET
    read -p "AWS Region (default: us-east-1): " AWS_REGION
    AWS_REGION=${AWS_REGION:-us-east-1}

    # Save S3 config
    cat > "$PROJECT_DIR/.s3-config" << EOF
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
S3_BUCKET=$S3_BUCKET
AWS_REGION=$AWS_REGION
EOF
    chmod 600 "$PROJECT_DIR/.s3-config"

    # Configure AWS CLI
    mkdir -p ~/.aws
    cat > ~/.aws/credentials << EOF
[default]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
EOF

    cat > ~/.aws/config << EOF
[default]
region = $AWS_REGION
EOF

    print_success "S3 configured"
fi

# =============================================================================
# CREATE BACKUP SCRIPT
# =============================================================================

print_status "Creating backup script..."

mkdir -p "$PROJECT_DIR/scripts"

cat > "$BACKUP_SCRIPT" << 'EOFBACKUP'
#!/bin/bash

# Daily Automated Backup Script
# Generated by setup_automated_backups.sh

set -e

# Configuration
PROJECT_DIR="PROJECT_DIR_PLACEHOLDER"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="$PROJECT_DIR/backups/daily-$TIMESTAMP"
S3_CONFIG="$PROJECT_DIR/.s3-config"

# Create backup directory
mkdir -p "$BACKUP_DIR"

cd "$PROJECT_DIR"
source .env 2>/dev/null || true

# Backup MySQL (Mautic)
if docker ps | grep -q "mautic-mysql"; then
    echo "[$(date)] Backing up MySQL..."
    docker-compose exec -T mysql mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > "$BACKUP_DIR/mysql.sql" 2>/dev/null
fi

# Backup PostgreSQL (Strapi)
if docker ps | grep -q "strapi-postgres"; then
    echo "[$(date)] Backing up PostgreSQL..."
    docker-compose exec -T postgres pg_dumpall -U strapi > "$BACKUP_DIR/postgres.sql" 2>/dev/null
fi

# Backup configuration
echo "[$(date)] Backing up configuration..."
cp .env "$BACKUP_DIR/" 2>/dev/null || true
cp docker-compose.yml "$BACKUP_DIR/" 2>/dev/null || true

# Backup Strapi project
if [[ -d "strapi" ]]; then
    echo "[$(date)] Backing up Strapi project..."
    tar czf "$BACKUP_DIR/strapi.tar.gz" -C . strapi --exclude='strapi/node_modules' --exclude='strapi/.cache' --exclude='strapi/build' 2>/dev/null || true
fi

# Backup Docker volumes
echo "[$(date)] Backing up volumes..."
docker run --rm -v mautic-n8n-stack_mautic_data_config:/source:ro -v "$BACKUP_DIR":/backup alpine tar czf /backup/mautic_config.tar.gz -C /source . 2>/dev/null || true
docker run --rm -v mautic-n8n-stack_n8n_data:/source:ro -v "$BACKUP_DIR":/backup alpine tar czf /backup/n8n_data.tar.gz -C /source . 2>/dev/null || true

# Create final archive
echo "[$(date)] Creating archive..."
cd "$PROJECT_DIR/backups"
tar czf "backup-$TIMESTAMP.tar.gz" -C "daily-$TIMESTAMP" .
rm -rf "daily-$TIMESTAMP"

# Upload to S3 if configured
if [[ -f "$S3_CONFIG" ]]; then
    source "$S3_CONFIG"
    echo "[$(date)] Uploading to S3..."
    aws s3 cp "backup-$TIMESTAMP.tar.gz" "s3://$S3_BUCKET/backup-$TIMESTAMP.tar.gz" --storage-class STANDARD_IA 2>/dev/null && echo "[$(date)] S3 upload successful" || echo "[$(date)] S3 upload failed"
fi

# Cleanup old local backups (keep last 7)
echo "[$(date)] Cleaning up old backups..."
find "$PROJECT_DIR/backups" -name "backup-*.tar.gz" -type f -mtime +7 -delete 2>/dev/null || true

echo "[$(date)] Backup completed: backup-$TIMESTAMP.tar.gz"
EOFBACKUP

# Replace placeholder
sed -i "s|PROJECT_DIR_PLACEHOLDER|$PROJECT_DIR|g" "$BACKUP_SCRIPT"
chmod +x "$BACKUP_SCRIPT"

print_success "Backup script created: $BACKUP_SCRIPT"

# =============================================================================
# SETUP CRON JOB
# =============================================================================

print_status "Setting up cron job..."

# Add to crontab (daily at 2 AM)
CRON_JOB="0 2 * * * $BACKUP_SCRIPT >> $PROJECT_DIR/logs/backup.log 2>&1"

# Check if already exists
if crontab -l 2>/dev/null | grep -q "$BACKUP_SCRIPT"; then
    print_warning "Cron job already exists"
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    print_success "Cron job added (runs daily at 2 AM UTC)"
fi

# =============================================================================
# TEST BACKUP
# =============================================================================

print_warning "Run test backup now? (Y/n)"
read -n 1 -r
echo
if [[ ${REPLY:-Y} =~ ^[Yy]$ ]]; then
    print_status "Running test backup..."
    $BACKUP_SCRIPT
    print_success "Test backup completed!"
fi

# =============================================================================
# SUMMARY
# =============================================================================

echo
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║           Automated Backup Setup Complete!               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo
echo "📋 Configuration:"
echo "   Schedule: Daily at 2:00 AM UTC"
echo "   Backup script: $BACKUP_SCRIPT"
echo "   Local retention: 7 days"
if [[ $ENABLE_S3 =~ ^[Yy]$ ]]; then
    echo "   S3 bucket: $S3_BUCKET"
    echo "   S3 region: $AWS_REGION"
    echo "   S3 storage class: STANDARD_IA"
fi
echo
echo "📂 Backups include:"
echo "   • MySQL database (Mautic data)"
echo "   • PostgreSQL database (Strapi + vectors)"
echo "   • Strapi project files"
echo "   • Configuration files"
echo "   • n8n workflows & credentials"
echo "   • Mautic configuration"
echo
echo "🔧 Management:"
echo "   View logs: tail -f $PROJECT_DIR/logs/backup.log"
echo "   List backups: ls -lh $PROJECT_DIR/backups/"
if [[ $ENABLE_S3 =~ ^[Yy]$ ]]; then
    echo "   List S3 backups: aws s3 ls s3://$S3_BUCKET/"
fi
echo "   Manual backup: $BACKUP_SCRIPT"
echo
print_success "Automated backups are now configured!"
echo
